# Generated by Django 4.2 on 2023-04-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaUpload', '0003_rename_file_files_arq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='arq',
            new_name='file',
        ),
    ]
