# Generated by Django 4.2 on 2023-04-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_crud_acid', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table01',
            new_name='Table1',
        ),
        migrations.RenameModel(
            old_name='Table02',
            new_name='Table2',
        ),
    ]
