# Generated by Django 4.2 on 2023-04-23 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_crud_acid', '0002_rename_table01_table1_rename_table02_table2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='video', to='db_crud_acid.category')),
                ('publishers', models.ManyToManyField(related_name='video', to='db_crud_acid.publishers')),
            ],
        ),
        migrations.DeleteModel(
            name='Table1',
        ),
        migrations.DeleteModel(
            name='Table2',
        ),
    ]
