# Generated by Django 4.2 on 2023-04-16 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
    ]
