# Generated by Django 4.2 on 2023-04-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_class', '0002_alter_person_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-age', 'name'], 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AddField(
            model_name='person',
            name='note',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('name',)},
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='Person_name_406296_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 18)), name='age_not_support'),
        ),
    ]
