# Generated by Django 4.2 on 2023-04-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_class', '0004_remove_person_age_not_support_person_age_not_support'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='age_not_support',
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 1)), name='age_not_support'),
        ),
    ]
