# Generated by Django 4.2 on 2023-04-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_class', '0005_remove_person_age_not_support_person_age_not_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='note',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date'))), name='start_end_dates'),
        ),
    ]
