# Generated by Django 4.2 on 2023-04-17 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_class', '0006_person_end_date_person_start_date_alter_person_note_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='age_not_support',
        ),
    ]
